spring:
  lifecycle:
    timeout-per-shutdown-phase: "20s"

server:
  port: 9080
  shutdown: "graceful"

management:
  endpoint:
    health:
      probes:
        enabled: true
      group:
        liveness:
          include: livenessStateProbeIndicator,diskSpace,refreshScope
        readyness:
          include: readinessStateProbeIndicator